### PR TITLE
[FEAT]: Waitlist API - ADD USER TO WAITLIST

### PR DESCRIPTION
**Pull request by Arnthorny**
## Description
This pull request introduces an endpoint for admins to manually add a user to the waitlist. 

The changes include:
 
* **Endpoint Addition:** Added `POST /api/v1/waitlist/admin` for deactivating invite links.
* **Error Handling:** Implemented checks for invalid data and unauthorized access.
* **Testing:** Added pytest cases to ensure functionality and edge cases are covered.
* **Bug Fixing:** Fixed a bug that affected the login functionality of users.
 
 
## Related Issue (Link to issue ticket)
[Issue Ticket](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/issues/238)
 
 ## Motivation and Context
This feature is essential to allow admins add users to a company's waitlist.
 
 ## How Has This Been Tested?
 * **Unit Tests:** Added tests to validate the addition of users to the database, handling of duplicate requests, and authorization failures.
* **Test Environment:** Tests were run using a mocked database instance to avoid interference with the production environment.

Tests include:
 
* Adding a user to the waitlist successfully.
* Handling attempts to add single user multiple times.
* Handling unauthorized access.

### Successful Request
Screenshot (442)

### Duplicated Request
Screenshot (443)

## Types of changes
* [x]  Bug fix (non-breaking change which fixes an issue)
* [x]  New feature (non-breaking change which adds functionality)
* [ ]  Breaking change (fix or feature that would cause existing functionality to change)
 
 ## Checklist:
 * [x]  My code follows the code style of this project.
 * [x]  My change requires a change to the documentation.
 * [x]  I have updated the documentation accordingly.
 * [x]  I have read the **CONTRIBUTING** document.
 * [x]  I have added tests to cover my changes.
 * [x]  All new and existing tests passed.

N.B: This PR was initially approved [here](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/pull/280) but it had to be remade as structural changes were made to the entire codebase

### CODE REVIEW

**Comment by joboy-dev** [comment]
Make a pull request to the dev branch not feature branch

**Comment by Arnthorny** [comment]
> Make a pull request to the dev branch not feature branch

Done chief

**Review by joboy-dev — CHANGES_REQUESTED** [review]
IDs for all models have been handled. Why are you adding IDs for them again
This is too much

Please change everything. This cannot be merged

**Comment by Arnthorny** [comment]
> IDs for all models have been handled. Why are you adding IDs for them again This is too much
> 
> Please change everything. This cannot be merged

I did not make those changes. The reason they show up here was because I tried to merge with the feature branch first before merging with the dev branch. But there's no problem. I'd close this PR and reopen another one

**Pull request closed without merging**
