### PR TITLE
added feature for admin users to be able to change topic

### PR DESCRIPTION
**Pull request by officialksolomon**
​

## Description

feat: add endpoint to update help center topics (Admin only)

- Implemented PATCH /api/v1/help-center/topics/{article_id} endpoint
- Added logic to handle topic updates for authorized admin users
- Replaced old topics with updated topics in the mock database
- Added unit tests to verify authorized access, input validation, and successful updates
- Ensured unauthorized users receive proper error responses

Resolves: #121

## Related Issue (Link to issue ticket)
https://github.com/hngprojects/hng_boilerplate_nestjs/issues/121

​

## Motivation and Context

This change is required to provide a secure way for administrators to update existing help center topics. The primary problem it solves is ensuring that only authorized users (specifically admins) can modify the content of help center topics. This helps maintain the integrity and accuracy of the information provided in the help center, ensuring that users receive reliable and updated information.

​

### How Has This Been Tested?

We tested the feature to make sure it works as expected. 

- I confirmed that an admin can update a topic, and the changes are saved correctly in the mock database.
- I verified that unauthorized users get a `403 Forbidden` error and their updates don't affect the database.
- I checked that invalid input, like an empty title, results in a `422 Unprocessable Entity` error with the right message.
- I used a mock database to simulate real database operations and reset it before each test to ensure accurate results.

These tests ensure the endpoint functions correctly, handles errors properly, and maintains data integrity.
​

## Screenshots (if appropriate - Postman, etc):

​

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
      ​

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by officialksolomon** [comment]
My test requires me to use some dependencies which are buggy from the main
code.
I will provide more details later

**Comment by officialksolomon** [comment]
Like when trying to use the admin user dependency I get an error message
"user object has no attribute is_super_admin and I don't want to touch your
files

**Comment by officialksolomon** [comment]
Changes made as requested.

**Comment by officialksolomon** [comment]
This code below is throwing error during test because `user.is_super_admin`
the dict object was accessed using dot notation.
And all the test so far in the repo, none has used authentication hence no
one as noticed.

def get_super_admin(db: Session = Depends(get_db), token: str = Depends(
oauth2_scheme)):
    user = get_current_user(db, token)
    if not user.is_super_admin:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="You do not have permission to access this resource",
        )
    return user

**Comment by Goketech** [comment]
the user model has been updated, pull from dev branch

**Comment by officialksolomon** [comment]
I have done that I know the user model is being updated but the test is
still complaining the test wants the attribute to be accessed as a
dictionary using the get method and not with Dot notation. When I try this
on my branch it worked but I didn't want to edit the model so that it
doesn't break other people's code

**Pull request closed without merging**
