### PR TITLE
refactor(products): change create product endpoint path

### PR DESCRIPTION
**Pull request by bruce-pain**
## Description
This pull request updates the route path for an API endpoint responsible for creating a new product. The existing endpoint path `/api/v1/products/{:org_id}` has been changed to `/api/v1/organizations/{:org_id}/products/` to align with the current organizational structure and improve API clarity.

## Related Issue (Link to issue ticket)
Issue #638 

## Motivation and Context

The change was made to follow best practices for REST API URLs

### Code Changes

- Updated the FastAPI route definition:
  - **Old Path**: `/api/v1/products/{:org_id}`
  - **New Path**: `/api/v1/organizations/{:org_id}/products/`
- Updated all references to the old route path in the codebase.
- Modified the endpoint logic to ensure the correct functionality with the new path.

### Testing

- Updated unit tests to cover the new route path.
- Performed integration tests to ensure end-to-end functionality remains intact.
- Conducted security tests to verify that only authenticated users can access the endpoint.

​
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
      ​

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by Goketech — DISMISSED** [review]

**Comment by bruce-pain** [comment]
@Goketech  @joboy-dev

**Comment by bruce-pain** [comment]
@Goketech  @joboy-dev

**Comment by bruce-pain** [comment]
@Goketech  @joboy-dev

**Review by Goketech — DISMISSED** [review]

**Comment by Goketech** [comment]
fix conflicts

**Comment by bruce-pain** [comment]
@Goketech fixed

**Review by Goketech — APPROVED** [review]

**Pull request merged**
