### PR TITLE
feat: Retrieve details of an organization

### PR DESCRIPTION
**Pull request by theijhay**
​

## Description

​

## Related Issue (Link to issue ticket)
#492 

​

## Motivation and Context

​

## How Has This Been Tested?

​

## Screenshots (if appropriate - Postman, etc):
Screenshot from 2024-08-03 22-58-04

​

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
      ​

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Goketech** [comment]
resolve your conflicts

**Review by Goketech — APPROVED** [review]

**Comment by Goketech** [comment]
fix conflicts

**Review by Goketech — CHANGES_REQUESTED** [review]
fix conflicts

**Comment by theijhay** [comment]
fixed @Goketech

**Review by Goketech — CHANGES_REQUESTED** [review]
make use of organization.py files

**Comment by theijhay** [comment]
@Goketech @joboy-dev Please review me

**Review by Goketech — APPROVED** [review]

**Review by SundayMba — APPROVED** [review]

**Comment by joboy-dev** [comment]
This your PR that is not correct. Where are the details??

**Review by joboy-dev — APPROVED** [review]

**Comment by theijhay** [comment]
@joboy-dev I have issues with
 the packages but all tests passed, you can test it and give me feedback boss

**Review by joboy-dev — APPROVED** [review]

**Comment by theijhay** [comment]
@SundayMba @Goketech @CodewithSegNet Please merge this before conflicts will arise again. i'm begging

**Pull request closed without merging**
