### PR TITLE
Implement Partial Update of User Profile Settings

### PR DESCRIPTION
**Pull request by 0FFSIDE1**
## Description
This pull request implements a RESTful API endpoint to handle partial updates of user profile settings. The endpoint allows authenticated users to modify specific parts of their profile information, such as name, email, or preferences. User preferences are stored as a JSON field in the user table of the database.

## Key Features
- API Endpoint Implementation:

- [ ] The endpoint is accessible at /api/v1/users/.

- [ ] Accepts HTTP PATCH requests.

- Data Validation and Authorization:

- [ ] Ensures the user making the request is authenticated.

- [ ] Validates incoming data for correctness and security.

- Updating User Profile:

- [ ] Updates the user's profile information in the database upon successful validation.

- [ ] Ensures critical fields (e.g., email) trigger appropriate verification processes if changed.

## Response:

- [ ] On success, returns a 200 OK status code with the updated profile information.

- [ ] On failure, returns appropriate error codes with descriptive messages.

## Related Issue
[Link to issue ticket](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/issues/86)

## Motivation and Context

The purpose of this implementation is to provide a secure and efficient backend service for users to update specific parts of their profile settings. The system ensures data validation and maintains user information integrity.

## How Has This Been Tested?

- [ ] Manual Testing: Verified the functionality using Postman by sending PATCH requests with different payloads.

- [ ] Unit Tests: Added unit tests to check validation, authentication, and successful updates.

- [ ] Integration Tests: Tested integration with other parts of the system to ensure seamless updates.

## Types of changes

- [ ]  New feature (non-breaking change which adds functionality)

 
## Checklist:
 

- [ ] My code follows the code style of this project.
- [ ]  My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ]  I have read the CONTRIBUTING document.
- [ ]  I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Code Implementation:
python
Copy code
@settings.patch("/users", status_code=status.HTTP_200_OK, response_model=success_response)
async def update_profile_settings(
    settings: UserAndProfileUpdate, 
    db: Session = Depends(get_db), 
    current_user: User = Depends(user_service.get_current_user)
):
    """
    Update the authenticated user's profile. This endpoint allows partial updates.
    """

    db_user = update_user_and_profile(db=db, user_id=current_user["id"], user_profile=settings)
    if db_user is None:
        raise HTTPException(status_code=404, detail="User not found")
    return success_response(
        status_code=200,
        message="Update created successfully",
        data=jsonable_encoder(db_user)
    )

### CODE REVIEW

**Comment by joboy-dev** [comment]
Merge conflict

**Review by joboy-dev — CHANGES_REQUESTED** [review]
Do this. All these profile settings files, all of the code should be in profile.py file for each of these folders. THis is for consistency sake

**Comment by 0FFSIDE1** [comment]
> Do this. All these profile settings files, all of the code should be in profile.py file for each of these folders. THis is for consistency sake

Done

**Comment by joboy-dev** [comment]
Merge conflict

**Comment by 0FFSIDE1** [comment]
> Merge conflict

Done please review

**Review by joboy-dev — APPROVED** [review]

**Comment by 0FFSIDE1** [comment]
i need second review

**Comment by Dev-wonderful** [comment]
Stale

**Pull request closed without merging**
