### PR TITLE
enhancement: update billing plan endpoints docs to show sample return data

### PR DESCRIPTION
**Pull request by traderstechie**
## Description
Update billing plan endpoints docs to show samples of expected data so frontend developers can easily integrate with the backend. Endpoint docs updated include:
- /api/v1/organisations/{organisation_id}/billing-plans
- /api/v1/organisations/billing-plans
- /api/v1/organisations/billing-plans/{billing_plan_id}
- /api/v1/organisations/billing-plans/{billing_plan_id}
 
## Related Issue
[[FIX]: Add Expected Data Samples To Docs For All Billing Plan Endpoints #941](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/issues/941)

 ## Motivation and Context
Frontend developers and others viewing the backend docs should be able to know exactly what to expect from each endpoint.
 

 ## How Has This Been Tested?
 * **Unit Tests:** Added tests to validate successful and failed requests as expected.
* **Test Environment:** Mocked database; to avoid interference with the production environment.

### Before The Update
boilerplate get all billing plan return value
boilerplate post billing plan return value

### After The Update
updated billing plan schema all
updated billing plan schema single

## Types of changes
* [x]  Bug fix (non-breaking change which adds functionality)
 

 ## Checklist:
 * [x]  My code follows the code style of this project.
 * [x]  My change requires a change to the documentation.
 * [x]  I have updated the documentation accordingly.
 * [x]  I have read the **CONTRIBUTING** document.
 * [x]  I have added tests to cover my changes.
 * [x]  All new and existing tests passed.

### CODE REVIEW

**Comment by JoshuaOloton** [comment]
This issue looks resolved already @traderstechie

**Comment by traderstechie** [comment]
> This issue looks resolved already @traderstechie

Not really. My PR is not about the endpoint functionality, but the docs that shows what's returned in the `data` key

**Comment by johnson-oragui** [comment]
You might as well fix the rest of the docs if this qualifies as an issue.

**Comment by traderstechie** [comment]
> You might as well fix the rest of the docs if this qualifies as an issue.

I believe it's something that should be done. If not now, then later. At least this one would bring attention to it. Without good docs, it'll be hard for non-contributors to integrate the product. It doesn't particularly matter if it qualifies as an issue now or not.

**Review by johnson-oragui — APPROVED** [review]

**Pull request merged**
