### PR TITLE
feat: add waitlist join endpoint

### PR DESCRIPTION
**Pull request by Laban254**
## Description

This PR introduces a new API endpoint `/api/v1/waitlists` to facilitate user to join the waitlist form on the website. 
functions:

-   Validates and sanitizes incoming user data, including email format and required fields (email, full name).
-   Stores user information securely in the database upon successful validation.
-   Sends a confirmation email to the user upon successful registration.
-   Handles errors gracefully, returning appropriate status codes and messages.

## Related Issue (Link to issue ticket)

Link to the issue :  [#328](rhttps://github.com/hngprojects/hng_boilerplate_python_fastapi_web/issues/328)

## Motivation and Context

The introduction of this API endpoint addresses the need for a streamlined process for users to join the waitlist for our product/service. It enhances user experience by automating the waitlist signup process and ensuring that user data is handled securely and efficiently.

## How Has This Been Tested?

I have  tested this feature using  Postman. The tests cover various scenarios, including valid and invalid inputs,  and error handling. All tests have passed successfully.  To run the test  
` python -m pytest  tests/v1/waitlist_test.py ` 

## Screenshots:
first

Screenshot from 2024-07-25 11-11-59

Screenshot from 2024-07-25 11-12-26

Test

Screenshot from 2024-07-24 16-46-49

Email

Screenshot from 2024-07-24 19-20-11

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

-  [x]  My code follows the code style of this project.
-   [ ] My change requires a change to the documentation.
-   [ ] I have updated the documentation accordingly.
-   [x] I have read the  **CONTRIBUTING**  document.
-   [x] I have added tests to cover my changes.
-   [x] All  tests passed.

### CODE REVIEW

**Review by Goketech — DISMISSED** [review]

**Comment by Laban254** [comment]
Hello @zxenonx  kindly review.

**Comment by Goketech** [comment]
@bolexs

**Comment by bolexs** [comment]
resolve conflicts and request second review from @joboy-dev

**Comment by Laban254** [comment]
> resolve conflicts and request second review from @joboy-dev

OKey, on it.

**Comment by Laban254** [comment]
Hello @joboy-dev  help me review it.

**Review by joboy-dev — DISMISSED** [review]

**Review by Goketech — APPROVED** [review]

**Review by Goketech — DISMISSED** [review]

**Review by zxenonx — APPROVED** [review]
Thanks @Laban254

**Comment by Laban254** [comment]
Thanks @zxenonx

**Pull request merged**
