### PR TITLE
feat:  add user to waitlist

### PR DESCRIPTION
**Pull request by Arnthorny**
## Description
This pull request introduces an endpoint for admins to manually add a user to the waitlist. 

The changes include:
 
* **Endpoint Addition:** Added `POST /api/v1/waitlist/admin` for deactivating invite links.
* **Error Handling:** Implemented checks for invalid data and unauthorized access.
* **Testing:** Added pytest cases to ensure functionality and edge cases are covered.
* **Bug Fixing:** Fixed a bug that affected the login functionality of users.
 
 
## Related Issue (Link to issue ticket)
[Issue Ticket](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/issues/238)
 
 ## Motivation and Context
This feature is essential to allow admins add users to a company's waitlist.
 
 ## How Has This Been Tested?
 * **Unit Tests:** Added tests to validate the addition of users to the database, handling of duplicate requests, and authorization failures.
* **Test Environment:** Tests were run using a mocked database instance to avoid interference with the production environment.

Tests include:
 
* Adding a user to the waitlist successfully.
* Handling attempts to add single user multiple times.
* Handling unauthorized access.

### Successful Request
Screenshot (442)

### Duplicated Request
Screenshot (443)

## Types of changes
* [x]  Bug fix (non-breaking change which fixes an issue)
* [x]  New feature (non-breaking change which adds functionality)
* [ ]  Breaking change (fix or feature that would cause existing functionality to change)
 
 ## Checklist:
 * [x]  My code follows the code style of this project.
 * [x]  My change requires a change to the documentation.
 * [x]  I have updated the documentation accordingly.
 * [x]  I have read the **CONTRIBUTING** document.
 * [x]  I have added tests to cover my changes.
 * [x]  All new and existing tests passed.

N.B: This PR was initially approved [here](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/pull/280) but it had to be remade as structural changes were made to the entire codebase

### CODE REVIEW

**Comment by CodewithSegNet** [comment]
No service for waitlist?

**Comment by Arnthorny** [comment]
The endpoint I implemented had no need for extra services. The ones in the codebase were sufficient.

**Review by CodewithSegNet — APPROVED** [review]
alright looks good however you'd have to wait for a mentor’s review.

**Comment by Arnthorny** [comment]
No problem. Thanks chief

**Comment by CodewithSegNet** [comment]
change PR name to feat: 
to follow proper naming convention

**Comment by Arnthorny** [comment]
> change PR name to feat: 
> to follow proper naming convention 

Done chief. 
Is there supposed to be a label added to the PR?

**Review by joboy-dev — DISMISSED** [review]

**Review by Goketech — APPROVED** [review]

**Review by joboy-dev — APPROVED** [review]

**Review by Goketech — APPROVED** [review]

**Review by zxenonx — APPROVED** [review]
Thanks @Arnthorny

**Pull request merged**
