### PR TITLE
feat: add Endpoint to retrieve all comments for a single blog.

### PR DESCRIPTION
**Pull request by johnson-oragui**
## Summary
api/v1/blogs/{blog_id}/comments?page=1&per_page=20
This endpoint retrieves comments associated with a single blog and the likes and dislikes associated with each comment.

​

## Description

Added a comment schema for comment related response. Created a service class to handle operations related to retrieving comments linked to a blog. The endpoint api/v1/blogs/{blog_id}/comments?page=1&per_page=20 will retrieve comments linked to the blog with the id, if the blog_id is a valid one. And the endpoint also works with pagination with 20 as the maximum page size.

​

## Related Issue (Link to issue ticket)

[Endpoint to retrieve all comments for a single blog.](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/issues/486)

​

## Motivation and Context

The new Feature is required because of the necessity to display every comment that is linked to a specific blog.
​

## How Has This Been Tested?

This endpoint was first tested with curl, and then with pytest, and finally with postman.
​

## Screenshots (if appropriate - Postman, etc):
page one
first page comments with pagination

​page two
second page comments

invalid blog Id
invalid blog Id

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
      ​

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by johnson-oragui** [comment]
@SundayMba 
@joboy-dev 
@CodewithSegNet 
@Goketech

**Comment by joboy-dev** [comment]
Fix merge conflict

**Comment by johnson-oragui** [comment]
> Fix merge conflict

Merge conflict has been resolved. Kindly review again.

**Comment by johnson-oragui** [comment]
@joboy-dev

**Review by Goketech — APPROVED** [review]

**Comment by johnson-oragui** [comment]
@CodewithSegNet 

need your second review

**Pull request closed without merging**
