### PR TITLE
feat: retrieve all product categories

### PR DESCRIPTION
**Pull request by Arnthorny**
## Description
Create an API endpoint that allows a user retrieve all product categories present in the database.​

The changes include:
 
* **Endpoint Addition:** Added `GET /api/v1/products/categories` for getting all product categories
* **Error Handling:** Implemented checks for unauthorized access.
* **Testing:** Added `pytest` cases to ensure functionality and edge cases are covered.
 
 
## Related Issue (Link to issue ticket)
[Issue Ticket](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/issues/65)

 ## Motivation and Context
This feature is essential to enable users retrieve all product categories currently in the database.
 
 ## How Has This Been Tested?
 * **Unit Tests:**
    * Added tests to validate the retrieval of categories from the database. 
    * Also tests to validate authentication failures.
* **Test Environment:** Tests were run using a mocked database instance to avoid interference with the production environment.

Tests include:
 
* Retrieving all categories from the database successfully.
* Handling unauthenticated access.

### Successful Request
image

### Unauthenticated Request
image

## Types of changes
* [x]  New feature (non-breaking change which adds functionality)
 
 ## Checklist:
 * [x]  My code follows the code style of this project.
 * [x]  My change requires a change to the documentation.
 * [x]  I have updated the documentation accordingly.
 * [x]  I have read the **CONTRIBUTING** document.
 * [x]  I have added tests to cover my changes.
 * [x]  All new and existing tests passed.

### CODE REVIEW

**Comment by bruce-pain** [comment]
@Goketech @joboy-dev

**Comment by bruce-pain** [comment]
@Goketech @joboy-dev

**Review by Goketech — APPROVED** [review]

**Comment by Arnthorny** [comment]
@SundayMba @CodewithSegNet

**Review by joboy-dev — COMMENTED** [review]
@Takinnuoye5

**Comment by joboy-dev** [comment]
Merge conflict

**Review by Goketech — DISMISSED** [review]

**Comment by Goketech** [comment]
fix conflicts

**Review by joboy-dev — APPROVED** [review]

**Comment by Arnthorny** [comment]
Merge conflicts resolved @joboy-dev @Takinnuoye5 @Goketech

**Review by joboy-dev — APPROVED** [review]

**Review by SundayMba — APPROVED** [review]

**Pull request merged**
