### PR TITLE
feat: create endpoint for user account deletion

### PR DESCRIPTION
**Pull request by KalminX**
# Description

I have fixed the user delete endpoint and wrote comprehensive tests for it to ensure functionality and reliability. The endpoint now allows authenticated users to delete their own accounts.

## Related Issue

This pull request addresses issue #123, which detailed the problems with the existing user delete endpoint and requested automated tests for this feature.

## Motivation and Context

This change was required to fix the malfunctioning user delete endpoint. It resolves the issue by ensuring users can delete their own accounts securely and includes tests to verify this functionality. This improvement enhances user management and data integrity within the application.

## How Has This Been Tested?

- The changes were tested using `pytest` in a controlled environment.
- Unit tests were written to cover different scenarios including successful account deletion, unauthorized access, and error handling.
- Integration tests were run to ensure the endpoint works correctly with the rest of the application.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by CodewithSegNet — CHANGES_REQUESTED** [review]
follow proper PR naming convention. eg, feat: create end …..

**Comment by KalminX** [comment]
> follow proper PR naming convention. eg, feat: create end …..

Done boss

**Review by SundayMba — DISMISSED** [review]
okay boss @Dev-wonderful

**Comment by joboy-dev** [comment]
Fix your merge conflicts

**Review by joboy-dev — DISMISSED** [review]

**Review by Goketech — APPROVED** [review]

**Review by CodewithSegNet — DISMISSED** [review]

**Review by joboy-dev — CHANGES_REQUESTED** [review]
Fix your tests

**Pull request closed without merging**
