### PR TITLE
 feat: endpoint to create blog post

### PR DESCRIPTION
**Pull request by chionz**
## Description

Added a new API endpoint to allow only a super admin to create a blog post. This includes implementing token-based authentication to ensure only users with the super admin role can access this functionality. The endpoint verifies the presence of a valid token in the Authorization header and validates the request body to ensure the required fields are provided and correctly formatted.

## Related Issue (Link to issue ticket)

[[FEAT]: Blog - Creating a Blog Post #113](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/issues/113)

## Motivation and Context

This change is required to restrict blog post creation to super admins only, enhancing security and ensuring only authorized personnel can create blog content. It solves the problem of unauthorized access to the blog creation endpoint.

## How Has This Been Tested?

Unit tests were implemented to cover various scenarios, including:
- Valid authorization token in the header
- Invalid authorization token
- Authorization token expiry time
- Invalid request bodies (missing required fields)
- Valid request bodies

Tests were run in a local development environment using a combination of automated testing tools and manual testing via Postman to ensure all functionalities work as expected and to verify the correct status codes and responses are returned for different cases.

## Screenshots (if appropriate - Postman, etc):

Screenshot from 2024-07-24 02-08-37

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Goketech** [comment]
fix the merge conflicts @chionz

**Review by Goketech — CHANGES_REQUESTED** [review]
revert all migrations

**Comment by Goketech** [comment]
close this pr and create a pr to dev branch

**Comment by chionz** [comment]
ok Sir

**Comment by chionz** [comment]
done, new pr on #444

**Pull request closed without merging**
