### PR TITLE
feat: Implement job retrieval endpoint

### PR DESCRIPTION
**Pull request by theijhay**
​

## Description

Develop an API endpoint to retrieve details of a specific job by its ID.

​

## Related Issue (Link to issue ticket)
This is the issue ticket #640 

​

## Motivation and Context

This change is required to enable users to fetch detailed information about a specific job using its ID. This feature enhances the functionality of the API by providing detailed job information retrieval capabilities, which is a common requirement for job listing applications.

​

## How Has This Been Tested?

The changes have been tested using:

- Unit tests with pytest to cover both valid and invalid job ID scenarios.
- Mocking the database with unittest.mock.MagicMock to simulate the database responses.
- Manual testing using Postman to verify the API responses for both existing and non-existing job IDs.

Screenshot from 2024-08-06 12-44-09

​

## Screenshots (if appropriate - Postman, etc):
Screenshot from 2024-08-06 06-31-12

​

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
      ​

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by joboy-dev** [comment]
Can you update this PR properly

**Comment by theijhay** [comment]
@joboy-dev How?

**Review by Goketech — APPROVED** [review]

**Comment by Goketech** [comment]
fix conflicts

**Comment by CodewithSegNet** [comment]
fix conflict

**Comment by theijhay** [comment]
@joboy-dev @Goketech @CodewithSegNet fixed

**Review by joboy-dev — APPROVED** [review]

**Pull request merged**
