### PR TITLE
Fix: Added Blog likes and Blog dislike tables

### PR DESCRIPTION
**Pull request by SundayMba**
Description
created additional tables and added additional field to the users model

i added is_verified and is_deleted to the users model to check for soft delete and users verification after registration.
and is_admin to is_super_admin
i also created additional tables for blog likes and dislikes

Related Issue (Link to issue ticket)
​

Motivation and Context
​the tables are need for people to deliver their issues

How Has This Been Tested?
​
yes
Screenshots (if appropriate - Postman, etc):
​

Types of changes
 [] - Bug fix (non-breaking change which fixes an issue)
 [x] - New feature (non-breaking change which adds functionality)
 [x] - Breaking change (fix or feature that would cause existing functionality to change)
​
Checklist:
 [x] - My code follows the code style of this project.
 [ ] - My change requires a change to the documentation.
 [] - I have updated the documentation accordingly.
 [x] - I have read the CONTRIBUTING document.
 [] - I have added tests to cover my changes.
 [x] - All new and existing tests passed.

### CODE REVIEW

**Review by joboy-dev — APPROVED** [review]
Good to go @bolexs @zxenonx @Dev-wonderful

**Comment by bolexs** [comment]
Use proper naming convention

**Comment by SundayMba** [comment]
please specify on which commit @bolexs

**Comment by bolexs** [comment]
> please specify on which commit @bolexs

Is it a fix/chore/ feat 
What exactly are you doing 
And fill in the information on the pr template

**Comment by Dev-wonderful** [comment]
Let your PR comment be properly formatted with markdown, like the default template

**Comment by SundayMba** [comment]
done @bolexs

**Comment by SundayMba** [comment]
please merge , those tables are needed by the members to implement their task @Dev-wonderful @bolexs

**Comment by joboy-dev** [comment]
@bolexs it's done

**Review by joboy-dev — APPROVED** [review]
Approved

**Review by bolexs — APPROVED** [review]

**Review by Dev-wonderful — APPROVED** [review]

**Pull request merged**
